---
output:
  pdf_document: default
  html_document: default
params:
    data: "."
    primers_cregion: "CRegionLog_table.tab"
---

```{r, message=FALSE, echo=FALSE, results="hide"}
# Setup
library(prestor)
library(knitr)
library(captioner)
if (!exists("tables")) { tables <- captioner(prefix="Table") }
if (!exists("figures")) { figures <- captioner(prefix="Figure") }
figures("primers_count", "Count of identified internal C-region")
figures("primers_hist", "Distribution of internal C-region match error rates.")
figures("primers_error", "Distribution of internal C-region match error rates, 
                          broken down by assigned C-region.")
```

```{r, echo=FALSE}
cregion_log <- loadLogTable(file.path(params$data, params$primers_cregion))
```

# Internal C-Region Identification

Words.

## Count of C-region matches

```{r, echo=FALSE}
plotMaskPrimers(cregion_log, titles=c("Assembled C-Region"), 
                style="count", max_error=0.4, sizing="figure")
```

`r figures("primers_count")`

## Internal C-region match error rates

```{r, echo=FALSE}
plotMaskPrimers(cregion_log, titles=c("Assembled C-Region"), 
                style="hist", max_error=0.4, sizing="figure")
```

`r figures("primers_hist")`

```{r, echo=FALSE}
plotMaskPrimers(cregion_log, titles=c("Assembled C-Region"), 
                style="error", max_error=0.4, sizing="figure")
```

`r figures("primers_error")`
