---
output:
  pdf_document: default
  html_document: default
params:
    data: "."
    headers_total: "Final_headers.tab"
    headers_unique: "Final-Unique_headers.tab"
    headers_atleast2: "Final-Unique-Atleast2_headers.tab"
---

```{R, message=FALSE, echo=FALSE, results="hide"}
# Setup
library(prestor)
library(knitr)
library(captioner)
if (!exists("tables")) { tables <- captioner(prefix="Table") }
if (!exists("figures")) { figures <- captioner(prefix="Figure") }
figures("headers_conscount", "Distribution of read counts for total (top) and unique sequences (bottom).")
figures("headers_dupcount", "Distribution of unique UMI counts for total unique sequences (top) 
                             and unique sequence represented at least twice (bottom).")
figures("headers_pr1", "Pie chart of C-region primer usage for total sequences.")
figures("headers_pr2", "Pie chart of C-region primer usage for unique sequences.")
figures("headers_pr3", "Pie chart of C-region primer usage for unique sequence represented at least twice.")
```

```{r, echo=FALSE}
parse_log_1 <- loadLogTable(file.path(params$data, params$headers_total))
parse_log_2 <- loadLogTable(file.path(params$data, params$headers_unique))
parse_log_3 <- loadLogTable(file.path(params$data, params$headers_atleast2))
```

# Summary of Final Output

Words.

## Distribution of read counts

```{r, echo=FALSE}
plotParseHeaders(parse_log_1, parse_log_2, 
                 titles=c("Total", "Unique"), 
                 style="count", primer="CREGION", count="CONSCOUNT", 
                 sizing="figure")
```

`r figures("headers_conscount")`

```{r, echo=FALSE}
plotParseHeaders(parse_log_2, parse_log_3, 
                 titles=c("Unique", "Atleast 2 Reads"), 
                 style="count", primer="CREGION", count="DUPCOUNT", 
                 sizing="figure")
```

`r figures("headers_dupcount")`

## C-region usage

```{r, echo=FALSE}
plotParseHeaders(parse_log_1, titles=c("Total"), 
                 style="primer", primer="CREGION", sizing="figure")
```

`r figures("headers_pr1")`

```{r, echo=FALSE}
plotParseHeaders(parse_log_2, titles=c("Unique"), 
                 style="primer", primer="CREGION", sizing="figure") 
```

`r figures("headers_pr2")`

```{r, echo=FALSE}
plotParseHeaders(parse_log_3,  titles=c("Unique Atleast 2 Reads"), 
                 style="primer", primer="CREGION", sizing="figure") 
```

`r figures("headers_pr3")`
