---
output:
  pdf_document: default
  html_document: default
params:
    data: "."
    primers_r1: "PrimerLogR1_table.tab"
    primers_r2: "PrimerLogR2_table.tab"
---

```{R, message=FALSE, echo=FALSE, results="hide"}
# Setup
library(prestor)
library(knitr)
library(captioner)
tables <- captioner(prefix="Table")
figures <- captioner(prefix="Figure")
figures("primers_hist", "Distribution of primer match error rates for 
                         read 1 (top) and read 2 (bottom).")
figures("primers_count", "Count of identified primers for 
                          read 1 (top) and read 2 (bottom).")
figures("primers_error", "Distribution of primer match error rates for 
                          read 1 (top) and read 2 (bottom), broken down 
                          by assigned primer.")
```

# Primer Identification

Words.

```{r, echo=FALSE}
primer_log_1 <- loadLogTable(file.path(params$data, params$primers_r1))
primer_log_2 <- loadLogTable(file.path(params$data, params$primers_r2))
plotMaskPrimers(primer_log_1, primer_log_2, titles=c("Read 1", "Read 2"), 
                style="hist", sizing="figure")
```

`r figures("primers_hist")`

```{r, echo=FALSE}
plotMaskPrimers(primer_log_1, primer_log_2, titles=c("Read 1", "Read 2"),
              style="count", sizing="figure")
```

`r figures("primers_count")`

```{r, echo=FALSE}
plotMaskPrimers(primer_log_1, primer_log_2, titles=c("Read 1", "Read 2"), 
                style="error", sizing="figure")
```

`r figures("primers_error")`
