---
output:
  pdf_document: default
  html_document: default
params:
    data: "."
    cregion: "cregion_table.tab"
---

```{r, message=FALSE, echo=FALSE, results="hide"}
# Setup
library(prestor)
library(knitr)
library(captioner)
if (!exists("tables")) { tables <- captioner(prefix="Table") }
if (!exists("figures")) { figures <- captioner(prefix="Figure") }
figures("cprimers_count", "Count of assigned C-regions. 
                           The bar height indicates the total reads assigned to 
                           the given C-region, stacked for those under the error 
                           rate threshold (Pass) and over the threshold (Fail).")
figures("cprimers_hist", "Distribution of C-region match error rates. 
                          The error rate is the percentage of mismatches between the 
                          C-region sequence and the read for the best 
                          matching C-region. The dotted line indicates the error
                          threshold used.")
figures("cprimers_error", "Distribution of C-region match error rates, 
                           broken down by assigned C-region. The error rate
                           is the percentage of mismatches between the 
                           C-region sequence and the read for the best 
                           matching C-region. The dotted line indicates the error
                           threshold used.")
```

```{r, echo=FALSE, warning=FALSE}
cregion_log <- loadLogTable(file.path(params$data, params$cregion))
```

# Constant Region Identification

The MaskPrimers tool is often used to identify constant region primers
used for isotype assignment by aligning against a portion of the C-region 
reference.

## Count of constant region matches

```{r, echo=FALSE, warning=FALSE}
plotMaskPrimers(cregion_log, titles=c("C-Region"), 
                style="count", max_error=0.3, sizing="figure")
```

`r figures("cprimers_count")`

## Constant region match error rates

```{r, echo=FALSE, warning=FALSE}
plotMaskPrimers(cregion_log, titles=c("C-Region"), 
                style="hist", max_error=0.3, sizing="figure")
```

`r figures("cprimers_hist")`

```{r, echo=FALSE, warning=FALSE}
plotMaskPrimers(cregion_log, titles=c("C-Region"), 
                style="error", max_error=0.3, sizing="figure")
```

`r figures("cprimers_error")`
